### ISSUE TITLE
permission issues

### ISSUE THREAD

**Issue by BenTheElder** [GoogleCloudPlatform/guest-test-infra#8]
it appears tide (The merge robot) from does not have permission to set contexts on this repo https://github.com/GoogleCloudPlatform/oss-test-infra

cc @fejta

**Comment by hopkiw** [comment]
Do you mean the tide components running in the OSS prow cluster cannot set contexts on -this- repo, guest-test-infra ? The only permissions we have granted on all of our prow-managed repos is to grant the google-oss-robot merge and comment permissions. If there's something else we should configure, can you explain?

**Comment by fejta** [comment]
Correct, @google-oss-robot needs write access to the repo in order to update status contexts. We are seeing the following error:

```yaml
jsonPayload: {
  component: "tide"   
  controller: "status-update"   
  error: "status code 404 not one of [201], body: {"message":"Not Found","documentation_url":"https://developer.github.com/v3/repos/statuses/#create-a-status"}"   
  file: "prow/tide/status.go:328"   
  func: "k8s.io/test-infra/prow/tide.(*statusController).setStatuses.func1"   
  level: "error"   
  msg: "Failed to set status context from "" to "pending"."   
  org: "GoogleCloudPlatform"   
  pr: 7   
  repo: "guest-test-infra"   
  sha: "1892aaa2fc554339b68fed4cecf02583eb5c1467"   
 }
```
